// Flaga si emoji nga kodi ISO 2-shkronjësh
export function flagFromCode(code) {
  if (!code || String(code).length !== 2) return '🏳️';
  const A = 0x1f1e6;
  try {
    return String.fromCodePoint(
      ...String(code).toUpperCase().split('').map(c => A + c.charCodeAt(0) - 65)
    );
  } catch (e) {
    return '🏳️';
  }
}

// Lista e të gjitha shteteve të botës (kodi ISO alpha-2 + emri në shqip)
export const COUNTRIES = [
  { code: 'XK', name: 'Kosovë' },
  { code: 'AD', name: 'Andorrë' },
  { code: 'AE', name: 'Emirate të Bashkuara Arabe' },
  { code: 'AF', name: 'Afganistan' },
  { code: 'AG', name: 'Antigua dhe Barbuda' },
  { code: 'AI', name: 'Anguilë' },
  { code: 'AL', name: 'Shqipëri' },
  { code: 'AM', name: 'Armeni' },
  { code: 'AO', name: 'Angolë' },
  { code: 'AR', name: 'Argjentinë' },
  { code: 'AT', name: 'Austri' },
  { code: 'AU', name: 'Australi' },
  { code: 'AW', name: 'Arubë' },
  { code: 'AX', name: 'Ishujt Alandë' },
  { code: 'AZ', name: 'Azerbajxhan' },
  { code: 'BA', name: 'Bosnje dhe Hercegovinë' },
  { code: 'BB', name: 'Barbados' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'BE', name: 'Belgjikë' },
  { code: 'BF', name: 'Burkina Faso' },
  { code: 'BG', name: 'Bullgari' },
  { code: 'BH', name: 'Bahrein' },
  { code: 'BI', name: 'Burundi' },
  { code: 'BJ', name: 'Benin' },
  { code: 'BL', name: 'Sen Bartelemi' },
  { code: 'BM', name: 'Bermude' },
  { code: 'BN', name: 'Brunei' },
  { code: 'BO', name: 'Bolivi' },
  { code: 'BQ', name: 'Karaibet Hollandeze' },
  { code: 'BR', name: 'Brazil' },
  { code: 'BS', name: 'Bahamas' },
  { code: 'BT', name: 'Butan' },
  { code: 'BV', name: 'Ishulli Buvetë' },
  { code: 'BW', name: 'Botsvana' },
  { code: 'BY', name: 'Bjellorusi' },
  { code: 'BZ', name: 'Belize' },
  { code: 'CA', name: 'Kanada' },
  { code: 'CC', name: 'Ishujt Kokos' },
  { code: 'CD', name: 'Kongo (Kinshasa)' },
  { code: 'CF', name: 'Republika e Afrikës Qendrore' },
  { code: 'CG', name: 'Kongo (Brazavil)' },
  { code: 'CH', name: 'Zvicër' },
  { code: 'CI', name: 'Bregu i Fildishtë' },
  { code: 'CK', name: 'Ishujt Kuk' },
  { code: 'CL', name: 'Kili' },
  { code: 'CM', name: 'Kamerun' },
  { code: 'CN', name: 'Kinë' },
  { code: 'CO', name: 'Kolumbi' },
  { code: 'CR', name: 'Kosta Rika' },
  { code: 'CU', name: 'Kubë' },
  { code: 'CV', name: 'Kap Verde' },
  { code: 'CW', name: 'Kurasao' },
  { code: 'CX', name: 'Ishulli i Krishtlindjes' },
  { code: 'CY', name: 'Qipro' },
  { code: 'CZ', name: 'Çeki' },
  { code: 'DE', name: 'Gjermani' },
  { code: 'DJ', name: 'Xhibuti' },
  { code: 'DK', name: 'Danimarkë' },
  { code: 'DM', name: 'Dominikë' },
  { code: 'DO', name: 'Republika Dominikanë' },
  { code: 'DZ', name: 'Algjeri' },
  { code: 'EC', name: 'Ekuador' },
  { code: 'EE', name: 'Estoni' },
  { code: 'EG', name: 'Egjipt' },
  { code: 'ER', name: 'Eritre' },
  { code: 'ES', name: 'Spanjë' },
  { code: 'ET', name: 'Etiopi' },
  { code: 'FI', name: 'Finlandë' },
  { code: 'FJ', name: 'Fixhi' },
  { code: 'FK', name: 'Ishujt Falkland' },
  { code: 'FM', name: 'Mikronezi' },
  { code: 'FO', name: 'Ishujt Faroe' },
  { code: 'FR', name: 'Francë' },
  { code: 'GA', name: 'Gabon' },
  { code: 'GB', name: 'Mbretëria e Bashkuar' },
  { code: 'GD', name: 'Grenada' },
  { code: 'GE', name: 'Gjeorgji' },
  { code: 'GF', name: 'Guajana Franceze' },
  { code: 'GG', name: 'Gernzi' },
  { code: 'GH', name: 'Gana' },
  { code: 'GI', name: 'Xhibraltar' },
  { code: 'GL', name: 'Groenlandë' },
  { code: 'GM', name: 'Gambi' },
  { code: 'GN', name: 'Gine' },
  { code: 'GP', name: 'Guadalupe' },
  { code: 'GQ', name: 'Gineja Ekuatoriale' },
  { code: 'GR', name: 'Greqi' },
  { code: 'GS', name: 'Gjeorgjia e Jugut dhe Ishujt Senduiç' },
  { code: 'GT', name: 'Guatemalë' },
  { code: 'GU', name: 'Guam' },
  { code: 'GW', name: 'Gine-Bisau' },
  { code: 'GY', name: 'Guajanë' },
  { code: 'HK', name: 'Hong Kong' },
  { code: 'HM', name: 'Ishulli Herd dhe Ishujt Makdonald' },
  { code: 'HN', name: 'Honduras' },
  { code: 'HR', name: 'Kroaci' },
  { code: 'HT', name: 'Haiti' },
  { code: 'HU', name: 'Hungari' },
  { code: 'ID', name: 'Indonezi' },
  { code: 'IE', name: 'Irlandë' },
  { code: 'IL', name: 'Izrael' },
  { code: 'IM', name: 'Ishulli i Njeriut' },
  { code: 'IN', name: 'Indi' },
  { code: 'IO', name: 'Territori Britanik i Oqeanit Indian' },
  { code: 'IQ', name: 'Irak' },
  { code: 'IR', name: 'Iran' },
  { code: 'IS', name: 'Islandë' },
  { code: 'IT', name: 'Itali' },
  { code: 'JE', name: 'Xherzi' },
  { code: 'JM', name: 'Xhamajkë' },
  { code: 'JO', name: 'Jordani' },
  { code: 'JP', name: 'Japoni' },
  { code: 'KE', name: 'Kenia' },
  { code: 'KG', name: 'Kirgizi' },
  { code: 'KH', name: 'Kamboxhia' },
  { code: 'KI', name: 'Kiribati' },
  { code: 'KM', name: 'Komore' },
  { code: 'KN', name: 'Saint Kits dhe Nevis' },
  { code: 'KP', name: 'Koreja e Veriut' },
  { code: 'KR', name: 'Koreja e Jugut' },
  { code: 'KW', name: 'Kuvajt' },
  { code: 'KY', name: 'Ishujt Kajman' },
  { code: 'KZ', name: 'Kazakistan' },
  { code: 'LA', name: 'Laos' },
  { code: 'LB', name: 'Liban' },
  { code: 'LC', name: 'Shën Luçia' },
  { code: 'LI', name: 'Lihtenshtajn' },
  { code: 'LK', name: 'Sri Lankë' },
  { code: 'LR', name: 'Liberi' },
  { code: 'LS', name: 'Lesoto' },
  { code: 'LT', name: 'Lituani' },
  { code: 'LU', name: 'Luksemburg' },
  { code: 'LV', name: 'Letoni' },
  { code: 'LY', name: 'Libi' },
  { code: 'MA', name: 'Marok' },
  { code: 'MC', name: 'Monako' },
  { code: 'MD', name: 'Moldavi' },
  { code: 'ME', name: 'Mal i Zi' },
  { code: 'MF', name: 'Sen Martin' },
  { code: 'MG', name: 'Madagaskar' },
  { code: 'MH', name: 'Ishujt Marshall' },
  { code: 'MK', name: 'Maqedonia e Veriut' },
  { code: 'ML', name: 'Mali' },
  { code: 'MM', name: 'Mjanmar' },
  { code: 'MN', name: 'Mongoli' },
  { code: 'MO', name: 'Makao' },
  { code: 'MP', name: 'Ishujt e Veriut Mariana' },
  { code: 'MQ', name: 'Martinikë' },
  { code: 'MR', name: 'Mauritani' },
  { code: 'MS', name: 'Montserat' },
  { code: 'MT', name: 'Maltë' },
  { code: 'MU', name: 'Mauritius' },
  { code: 'MV', name: 'Maldive' },
  { code: 'MW', name: 'Malavi' },
  { code: 'MX', name: 'Meksikë' },
  { code: 'MY', name: 'Malajzi' },
  { code: 'MZ', name: 'Mozambik' },
  { code: 'NA', name: 'Namibi' },
  { code: 'NC', name: 'Kaledonia e Re' },
  { code: 'NE', name: 'Niger' },
  { code: 'NF', name: 'Ishulli Norfolk' },
  { code: 'NG', name: 'Nigeri' },
  { code: 'NI', name: 'Nikaragua' },
  { code: 'NL', name: 'Holandë' },
  { code: 'NO', name: 'Norvegji' },
  { code: 'NP', name: 'Nepal' },
  { code: 'NR', name: 'Nauru' },
  { code: 'NU', name: 'Niue' },
  { code: 'NZ', name: 'Zelandë e Re' },
  { code: 'OM', name: 'Oman' },
  { code: 'PA', name: 'Panama' },
  { code: 'PE', name: 'Peru' },
  { code: 'PF', name: 'Polinezia Franceze' },
  { code: 'PG', name: 'Papua Guineja e Re' },
  { code: 'PH', name: 'Filipine' },
  { code: 'PK', name: 'Pakistan' },
  { code: 'PL', name: 'Poloni' },
  { code: 'PM', name: 'Sen Pjer dhe Mikelon' },
  { code: 'PN', name: 'Pitkern' },
  { code: 'PR', name: 'Portoriko' },
  { code: 'PS', name: 'Palestinë' },
  { code: 'PT', name: 'Portugali' },
  { code: 'PW', name: 'Palau' },
  { code: 'PY', name: 'Paraguaj' },
  { code: 'QA', name: 'Katar' },
  { code: 'RE', name: 'Reunion' },
  { code: 'RO', name: 'Rumuni' },
  { code: 'RS', name: 'Serbi' },
  { code: 'RU', name: 'Rusi' },
  { code: 'RW', name: 'Ruandë' },
  { code: 'SA', name: 'Arabi Saudite' },
  { code: 'SB', name: 'Ishujt Solomon' },
  { code: 'SC', name: 'Sejshel' },
  { code: 'SD', name: 'Sudan' },
  { code: 'SE', name: 'Suedi' },
  { code: 'SG', name: 'Singapor' },
  { code: 'SH', name: 'Shën Elena' },
  { code: 'SI', name: 'Slloveni' },
  { code: 'SJ', name: 'Svalbard dhe Jan Majen' },
  { code: 'SK', name: 'Sllovaki' },
  { code: 'SL', name: 'Siera Leone' },
  { code: 'SM', name: 'San Marino' },
  { code: 'SN', name: 'Senegal' },
  { code: 'SO', name: 'Somali' },
  { code: 'SR', name: 'Surinam' },
  { code: 'SS', name: 'Sudani i Jugut' },
  { code: 'ST', name: 'Sao Tome dhe Principe' },
  { code: 'SV', name: 'Salvador' },
  { code: 'SX', name: 'Sen Martin (Holandez)' },
  { code: 'SY', name: 'Siri' },
  { code: 'SZ', name: 'Esvatini' },
  { code: 'TC', name: 'Ishujt Turks dhe Kaikos' },
  { code: 'TD', name: 'Çad' },
  { code: 'TF', name: 'Territoret Jugore Franceze' },
  { code: 'TG', name: 'Togo' },
  { code: 'TH', name: 'Tajlandë' },
  { code: 'TJ', name: 'Taxhikistan' },
  { code: 'TK', name: 'Tokelau' },
  { code: 'TL', name: 'Timor-Leste' },
  { code: 'TM', name: 'Turkmenistan' },
  { code: 'TN', name: 'Tunizi' },
  { code: 'TO', name: 'Tonga' },
  { code: 'TR', name: 'Turqi' },
  { code: 'TT', name: 'Trinidad dhe Tobago' },
  { code: 'TV', name: 'Tuvalu' },
  { code: 'TW', name: 'Tajvan' },
  { code: 'TZ', name: 'Tanzani' },
  { code: 'UA', name: 'Ukrainë' },
  { code: 'UG', name: 'Ugandë' },
  { code: 'UM', name: 'Ishujt e Vegjël Periferikë të SHBA' },
  { code: 'US', name: 'SHBA' },
  { code: 'UY', name: 'Uruguaj' },
  { code: 'UZ', name: 'Uzbekistan' },
  { code: 'VA', name: 'Vatikan' },
  { code: 'VC', name: 'Shën Vinsent dhe Grenadinet' },
  { code: 'VE', name: 'Venezuela' },
  { code: 'VG', name: 'Ishujt Xhiroga Britanike' },
  { code: 'VI', name: 'Ishujt Xhiroga e SHBA' },
  { code: 'VN', name: 'Vietnam' },
  { code: 'VU', name: 'Vanuatu' },
  { code: 'WF', name: 'Uollis dhe Futuna' },
  { code: 'WS', name: 'Samoë' },
  { code: 'YE', name: 'Jemen' },
  { code: 'YT', name: 'Majot' },
  { code: 'ZA', name: 'Afrika e Jugut' },
  { code: 'ZM', name: 'Zambi' },
  { code: 'ZW', name: 'Zimbabve' },
];

// Lookup flag + emër nga vlera e ruajtur (emër ose kod)
export function countryInfo(value) {
  if (!value) return null;
  const v = String(value).trim();
  const byName = COUNTRIES.find(c => c.name.toLowerCase() === v.toLowerCase());
  if (byName) return { code: byName.code, name: byName.name, flag: flagFromCode(byName.code) };
  const byCode = COUNTRIES.find(c => c.code.toLowerCase() === v.toLowerCase());
  if (byCode) return { code: byCode.code, name: byCode.name, flag: flagFromCode(byCode.code) };
  // Vlerë manuale (tekst i lirë) — ktheje pa flamur
  return { code: null, name: v, flag: null };
}